test : ../heap/MaxHeap.h ../heap/MaxHeap.cpp PriorityQueue.h PriorityQueue.cpp test.cpp
	g++ -o ../output/PriorityQueueTest ../heap/MaxHeap.h ../heap/MaxHeap.cpp PriorityQueue.h PriorityQueue.cpp test.cpp
	../output/PriorityQueueTest
