quickSort : quickSort.cpp test.cpp
	g++ -o ../../output/quickSortTest quickSort.cpp test.cpp
	../../output/quickSortTest
countSort : countSort.cpp test.cpp
	g++ -o ../../output/countSortTest countSort.cpp test.cpp
	../../output/countSortTest
bucketSort : bucketSort.cpp test.cpp
	g++ -o ../../output/bucketSortTest bucketSort.cpp test.cpp
	../../output/bucketSortTest
	